appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HWqGc7yLDobrK6j5pa5a2FtS4qZtV6fwNqc99RPUOfhA77qPqI4+rtHB8RaG4G/DTDYrOdaNcgT+PpDqf/WI/AisCA57AM0qBWJjtrSMrd7HWL1fsZ2jJK/v5lDOum2un+cfcAKnduhwEtu2AK8NEKq7TfJo53tQ0r648kzjOUeijN2shPqrChtXH8NdDujhemSahYIkpi3Dn9L0H2yTAo8MwwHF8xrDp72oB+r2RzgBO752jLjl6RtqOUYIp63O7zuLSK6FIGkzqG+wmAcMcHcACnbQO6c1iCz8BBswF9FFQVyCBBN4BbrIF3AVNAqF6bt+jKosEA6KSI7Z3XHN6GI1CtjA6SLhi4Fcsql4Fn29LgdEFY0RewZxN1xHvFzjkzvQThLaEPXc1KezZWcJuZ5qsI2SJ9S+6Vrf9oB2OQjYrSQXt5S9OUQFLLFmQdEZE/48iEHhLB/rYVX4P/6BUbBSVL76LWsp6pVErMcxVNSbTtmeyqxlafU5xmvPl8H5hLrtV/pyk/bAhpA18VQNfV2pRh4v3xtp98tQNwxDa2Q4M43tf8pH7kFK0+PNbJE+IKB5p6qoMU4EmDDaUislHeXmF+uwmMQfnM6bRExu20PEuGay0pRcFqDw5v8hbSc2/MbwcBYV3PI8EAFXK7DfY9KcvlUi7C7ujfOyYBqmcnQ=}
